FROM nvidia/cuda:12.6.0-cudnn-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        ffmpeg \
        wget \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.worker.txt .

RUN python3 -m pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements.worker.txt

COPY app ./app

CMD ["python3", "-m", "dramatiq", "app.worker.tasks", "--processes", "1", "--threads", "1"]